Parameterize postgres resource requests, changes to create-sample-resources

diff --git a/create-sample-resources b/create-sample-resources
--- a/create-sample-resources
+++ b/create-sample-resources
@@ -1,13 +1,26 @@
 #!/bin/bash
 
+exit_with_error() {
+  echo "[Error] $@"
+  exit 1
+}
+
+exit_on_error() {
+  if [ $? -ne 0 ]; then
+    exit_with_error $1
+  fi
+}
+
 fog="./fog"
 # fog=fog
 
 # Set context
 $fog set-context --org 'sandbox' --workspace 'dev-sandbox' --environment 'dev'
+exit_on_error "Failed to set context, aborting."
 
 # Create API
 $fog create api --name 'dev-sandbox' --description 'Developer Sandbox API' --provider 'default-kong'
+exit_on_error "Failed to create API resource, aborting."
 
 # Create Containers
 $fog create container -f examples/nginx-container.json \
@@ -19,25 +32,23 @@ for f in examples/*-lambda.json; do
   $fog create lambda -f $f --provider 'default-laser'
 done
 
-$fog create api --name 'test-api' --description 'Test API' --provider 'default-kong'
-
 ## Hello lambda API endpoints
 
-$fog create api-endpoint -f examples/dotnet-hello-api-endpoint.json --api 'test-api' --lambda 'dotnet-hello'
-$fog create api-endpoint -f examples/nashorn-hello-api-endpoint.json --api 'test-api' --lambda 'nashorn-hello'
-$fog create api-endpoint -f examples/hello-lodash-api-endpoint.json --api 'test-api' --lambda 'hello-lodash'
-$fog create api-endpoint -f examples/python2-hello-api-endpoint.json --api 'test-api' --lambda 'python2-hello'
-$fog create api-endpoint -f examples/python3-hello-api-endpoint.json --api 'test-api' --lambda 'python3-hello'
+$fog create api-endpoint -f examples/dotnet-hello-api-endpoint.json --api 'dev-sandbox' --lambda 'dotnet-hello'
+$fog create api-endpoint -f examples/nashorn-hello-api-endpoint.json --api 'dev-sandbox' --lambda 'nashorn-hello'
+$fog create api-endpoint -f examples/hello-lodash-api-endpoint.json --api 'dev-sandbox' --lambda 'hello-lodash'
+$fog create api-endpoint -f examples/python2-hello-api-endpoint.json --api 'dev-sandbox' --lambda 'python2-hello'
+$fog create api-endpoint -f examples/python3-hello-api-endpoint.json --api 'dev-sandbox' --lambda 'python3-hello'
 
 ## Other Examples
 
-$fog create api-endpoint -f examples/factorial-api-endpoint.json --api 'test-api' --lambda 'factorial'
-$fog create api-endpoint -f examples/sales-api-endpoint.json --api 'test-api' --lambda 'sales'
-$fog create api-endpoint -f examples/slack-sales-api-endpoint.json --api 'test-api' --lambda 'slack-sales'
-$fog create api-endpoint -f examples/sms-hello-api-endpoint.json --api 'test-api' --lambda 'sms-hello'
+$fog create api-endpoint -f examples/factorial-api-endpoint.json --api 'dev-sandbox' --lambda 'factorial'
+$fog create api-endpoint -f examples/sales-api-endpoint.json --api 'dev-sandbox' --lambda 'sales'
+$fog create api-endpoint -f examples/slack-sales-api-endpoint.json --api 'dev-sandbox' --lambda 'slack-sales'
+$fog create api-endpoint -f examples/sms-hello-api-endpoint.json --api 'dev-sandbox' --lambda 'sms-hello'
 
 ## Kafka
 
-$fog create api-endpoint -f examples/kafka-consumer-api-endpoint.json --api 'test-api' --lambda 'kafkaConsumer'
-$fog create api-endpoint -f examples/kafka-producer-api-endpoint.json --api 'test-api' --lambda 'kafkaProducer'
+$fog create api-endpoint -f examples/kafka-consumer-api-endpoint.json --api 'dev-sandbox' --lambda 'kafkaConsumer'
+$fog create api-endpoint -f examples/kafka-producer-api-endpoint.json --api 'dev-sandbox' --lambda 'kafkaProducer'
 
